### ISSUE TITLE
1.20.1 Ksyxis

### ISSUE THREAD

**Issue by Krimatoria** [TeamPeril/Sculk-Hoard#61] opened 2024-07-13 01:06 UTC
Forge 47.3.5 1.20.1

I do not know what I found, but it is clearly some kind of incompatibility with Ksuxis.

I was building an assembly and when I turned on your mod, Ksuxis stopped creating the world very quickly, as it usually does, and the generation of the world lasted a very long time, hanging at 15 percent always. 

I will be able to search for the answer in the logs only in the sun, most likely, but perhaps you can already check something.

sculkhorde-1.20.1-0.9.7.jar
Ksyxis 1.3.2 modrinth

**Comment by Mikeatron-User** [comment] 2024-07-13 14:39
Duplicate of #48 https://github.com/TeamPeril/Sculk-Horde/issues/48

**Closed as completed by Mikeatron-User** 2024-07-13 14:39 UTC
Labels: duplicate
